### ISSUE TITLE
generating ID_BLOCK

### ISSUE THREAD

**Issue by aep** [google/go-sev-guest#20]
do we have a tool to generate an id block?

unfortunately i can't really figure out the structure from the sev doc.
 
as far as i understand this 

https://github.com/google/go-sev-guest/blob/29213bc42abeabf38d1c525aea374d1c44e578bf/abi/abi.go#L367

is the result of secure processor already doing its thing with the idblock and not the input format

**Comment by aep** [comment]
Thanks. This is very interesting because it's confusing what this is even supposed to be used for. My customer insists that the idblock is  signed by their private key, but I'm not sure how they could at all, since it includes the hash of ovmh. 

Does Google just provide a list of signer pubkeys somewhere ?

**Comment by aep** [comment]
anyway, is it of value to put a tool that does generate the idblock in this package or rather not?

**Comment by deeglaze** [comment]
The idblock generation code is likely to be a separate software package, since this is only for client-side attestation report fetching and fundamental report verification logic. Owner responsibilities that deal with OVMF specifically deserves a separate project.

As for signing the ID_BLOCK, you're facing a difficult management problem. All the CSPs currently manage their own firmware, and update it frequently. If you require that the firmware is signed by a non-CSP owner, then you're asking for one of a few things:

1. Bring your own firmware, ID_BLOCK, and ID_AUTH. This is a rather sizable product ask since it's difficult to make firmware management a good customer experience when your hypervisor is not readily usable outside the cloud. I know Azure has a preview of trying out bringing your own firmware, but you'll be using their source and build tools as a starting point in order to have a chance of having it be operational in their cloud. 
2. The CSP provides a way for a customer to provide their own ID_BLOCK and ID_AUTH for the CSP's firmware. I can think of a few ways this could work:
   
   a.   The CSP provides a way for a VM owner to sign any new CSP firmware's ID_BLOCK through an external key management system, so that the owner to automatically agree to an access justification for routine updates provided the CSP's golden measurement signature passes.

   b.    The CSP's ID_BLOCK, ID_AUTH comes from a repository managed with a new project API, and the CSP also provides an API that lists the n-most-recent firmware releases that you might see in production. The customer can have their own workflow to fetch the firmware binaries, compute the new ID_BLOCK and ID_AUTH struct, and then push those to the repository.

In all these instances, you're asking for a lot of work. I'm not saying that it wouldn't get done since there might be enough customer demand to amortize the costs, but you'd need to talk to some product managers.

**Comment by deeglaze** [comment]
If you're satisfied enough with this answer, please close this issue. If not, let me know what else you'd like to know.

**Comment by aep** [comment]
Thanks! Sounds like we will not contribute an idblock Generation thing to this project because it's not generic enough.

**Comment by shuk777** [comment]
Hi, @aep. I wrote a tool to generate id block [here](https://github.com/shuk777/sev-snp-measure/tree/feature/id-block).

If you still need this tool, feel free to use it and leave comments. Now I'm waiting for the approval for my PR https://github.com/IBM/sev-snp-measure/pull/10
